### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by abcjan88** [hadish100/kn-panel#2]
i have problem to install first iclone repo to my server and chhmod with command sudo chmod +x install.sh and bash install.sh 
but not install and show alien word please help me iwant to use this panel 

thank you for answer 

![สกรีนช็อต 2024-10-08 160511](https://github.com/user-attachments/assets/7bf18a01-d744-4821-ab2a-1ce8df46d3f5)

**Comment by hadish100** [comment]
Hello, the install.sh file is actually encypted. The panel currently comes with limited edition and you have to buy it in order to use it.

**Comment by abcjan88** [comment]
Ok thanks you 😁😁😁
